name: wyn-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build CLI
      run: dotnet test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: ['win-x64', 'linux-x64']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build & publish CLI
      run: dotnet publish src/wyn.cli/wyn.cli.csproj -r ${{ matrix.rid }} -c Release -p:PublishSingleFile=true --self-contained false --output publish/${{ matrix.rid }}
    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.rid }}
        path: |
          publish/${{ matrix.rid }}
  release:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
    
