name: wyn-build-0.1.${{ github.run_number }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
#    - name: Build CLI
#      run: dotnet test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: ['win-x64', 'linux-x64']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build & publish CLI
      run: dotnet publish src/wyn.cli/wyn.cli.csproj -r ${{ matrix.rid }} -c Release -p:PublishSingleFile=true --self-contained false --output publish/${{ matrix.rid }}
    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.rid }}
        path: |
          publish/${{ matrix.rid }}
  release:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
    - name: Create Framework packages
      run: |
        tar cvzf wyn.tar.gz linux-x64/wyn
        zip -q wyn.zip win-x64/wyn.exe
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "0.1.${{ github.run_number }}-pre"
        files: |
          wyn.tar.gz
          wyn.zip
    
