name: wyn-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build CLI
      run: dotnet test
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build & publish CLI
      run: dotnet publish src/wyn.cli/wyn.cli.csproj -r win-x64 -c Release -p:PublishSingleFile=true --self-contained false
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build & publish CLI
      run: dotnet publish src/wyn.cli/wyn.cli.csproj -r linux-x64 -c Release -p:PublishSingleFile=true --self-contained false
  release:
    needs: [test, build-win, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
    
